name: Festival Scraper

on:
  workflow_dispatch:


jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - run: python festivals.py

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add hindu_festivals_2026_full.json
          git commit -m "update data" || echo "no changes"
          git push
